name: machinespirit
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  nyxx: 2.0.0-rc.12
  nyxx_commander: any
  nyxx_interactions: any
  d20: any
  toml: any
  cron: any
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
