name: machinespirit
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  nyxx: ^1.1.0-dev
  nyxx_commander: ^1.1.0-dev
  nyxx_interactions: any
  dart_dice_parser: any
  toml: any
  cron: any
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
