name: machinespirit
description: Discord Dice roller bot for Wrath and Glory
version: 1.5.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  nyxx: 3.2.6
  nyxx_commander: any
  nyxx_interactions: any
  d20: any
  toml: any
  cron: any
  mongo_dart: any
  http: any
  html: any
  deep_pick: any
  time_ago_provider: any
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
